# Generated by Django 4.1.5 on 2023-02-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_events_description_alter_reservation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='title',
            new_name='name',
        ),
    ]
